#ifndef CONST_HH
#define CONST_HH

enum MessageConst
{
    MESSAGE_ID_SIZE = 16,
    MESSAGE_ADDRESS_SIZE = 32,
    MESSAGE_HEX_ADDRESS_SIZE = 64,
    MESSAGE_MAX_SIZE = 4096,

    MESSAGE_LENGTH_SECTION_SIZE = 2,
    MESSAGE_ENC_ALGORITHM_SIZE = 1,

    MESSAGE_HEADER_OFFSET = 0,
    MESSAGE_SIZE_SECTION_OFFSET = MESSAGE_HEADER_OFFSET,
    MESSAGE_ENC_ALGORITHM_OFFSET = MESSAGE_SIZE_SECTION_OFFSET + MESSAGE_LENGTH_SECTION_SIZE,
    
    MESSAGE_HEADER_SIZE = MESSAGE_LENGTH_SECTION_SIZE + MESSAGE_ENC_ALGORITHM_SIZE,

    MESSAGE_PAYLOAD_OFFSET = MESSAGE_HEADER_OFFSET + MESSAGE_HEADER_SIZE
};

enum MessageEncryptionAlgorithm
{
    MESSAGE_ENC_ALGORITHM_NONE = 0x00,
    MESSAGE_ENC_ALGORITHM_AES = 0x01,
    MESSAGE_ENC_ALGORITHM_RSA = 0x02
};

#endif