#ifndef CONST_HH
#define CONST_HH

enum MessageConst
{
    MESSAGE_ENC_PUBKEY_SIZE = 512,
    SESSION_KEY_SIZE = 32,
    SESSION_ID_SIZE = 16,
    ENCODED_SESSION_ID_SIZE = 24,

    MESSAGE_ADDRESS_SIZE = 32,
    MESSAGE_HEX_ADDRESS_SIZE = 64,
    MESSAGE_MAX_SIZE = 4096,

    MESSAGE_LENGTH_SECTION_SIZE = 2,
    MESSAGE_ENC_ALGORITHM_SIZE = 1,

    MESSAGE_HEADER_OFFSET = 0,
    MESSAGE_SIZE_SECTION_OFFSET = MESSAGE_HEADER_OFFSET,
    MESSAGE_ENC_ALGORITHM_OFFSET = MESSAGE_SIZE_SECTION_OFFSET + MESSAGE_LENGTH_SECTION_SIZE,

    MESSAGE_HEADER_SIZE = MESSAGE_LENGTH_SECTION_SIZE + MESSAGE_ENC_ALGORITHM_SIZE,

    MESSAGE_PAYLOAD_OFFSET = MESSAGE_HEADER_OFFSET + MESSAGE_HEADER_SIZE
};

enum MessageTypes
{
    MESSAGE_HANDSHAKE = 0x00,
    MESSAGE_ENC_NONE = 0x01,
    MESSAGE_ENC_AES = 0x02,
    MESSAGE_ENC_RSA = 0x03,
    MESSAGE_EXIT = 0x04
    
};

#endif